//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad.Cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id { get; set; }
        public string llave { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string descricpion { get; set; }
        public string idTipoCliente { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idSuscriptor { get; set; }
        public Nullable<int> idOperacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string telefono { get; set; }
        public string telefonoMovil { get; set; }
        public string correo { get; set; }
        public string genero { get; set; }
        public string direccion { get; set; }
        public string referencia { get; set; }
        public string banco { get; set; }
        public string cuentaBanco { get; set; }
        public Nullable<int> importe { get; set; }
        public Nullable<int> saldo { get; set; }
        public string rutaFoto { get; set; }
        public string urlFoto { get; set; }
        public string fechaNacimiento { get; set; }
        public string fecha { get; set; }
        public string fechaEntrega { get; set; }
        public string fechaRegistro { get; set; }
        public Nullable<int> idSocio { get; set; }
        public string fechaEstatus { get; set; }
        public Nullable<short> estatus { get; set; }
    }
}
