//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoCaptura
    {
        public int IdAccesoCaptura { get; set; }
        public Nullable<int> IdDefinicionCaptura { get; set; }
        public string Tipo { get; set; }
        public string Acceso { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
