//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplicacion()
        {
            this.BitacoraError = new HashSet<BitacoraError>();
        }
    
        public int IdAplicacion { get; set; }
        public string Clave { get; set; }
        public Nullable<int> IdSistema { get; set; }
        public Nullable<int> IdModuloSistema { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string IdAutorCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string IdAutorActualizacion { get; set; }
        public string Capa { get; set; }
        public string Clase { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraError> BitacoraError { get; set; }
    }
}
