//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraError
    {
        public int IdErrorAplicacion { get; set; }
        public Nullable<int> IdSistema { get; set; }
        public Nullable<int> IdModulo { get; set; }
        public Nullable<int> IdAplicacion { get; set; }
        public string Severidad { get; set; }
        public string Componente { get; set; }
        public string Tipo { get; set; }
        public string Clase { get; set; }
        public Nullable<int> IdError { get; set; }
        public string Mensaje { get; set; }
        public string Descripcion { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
        public virtual ErrorPersonalizado ErrorPersonalizado { get; set; }
    }
}
