//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Clave { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaTerminacion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public Nullable<decimal> CostoHora { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public string NumeroSeguro { get; set; }
        public Nullable<int> IdSuscriptor { get; set; }
        public string IdEstatus { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdEmpledoSuperior { get; set; }
    }
}
