//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public int OBJECTID { get; set; }
        public string Nombre { get; set; }
        public decimal AreaKm2 { get; set; }
        public Nullable<decimal> XCentroide { get; set; }
        public Nullable<decimal> YCentroide { get; set; }
        public Nullable<short> IdPais { get; set; }
        public string ClaveEstado { get; set; }
        public Nullable<int> MetaTerritorial { get; set; }
        public Nullable<int> AvanceTerritorial { get; set; }
        public Nullable<short> Tipo { get; set; }
        public decimal Shape_STArea__ { get; set; }
        public decimal Shape_STLength__ { get; set; }
        public decimal Shape_STArea_1 { get; set; }
        public decimal Shape_STLength_1 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    }
}
