//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcionMenu
    {
        public int IdOpcionMenu { get; set; }
        public int IdMenu { get; set; }
        public Nullable<short> Orden { get; set; }
        public string Titulo { get; set; }
        public string Ayuda { get; set; }
        public string TipoComando { get; set; }
        public string Comando { get; set; }
        public string Caracteristicas { get; set; }
        public string Parametros { get; set; }
        public Nullable<int> IdPrivilegio { get; set; }
        public string Color { get; set; }
        public string Imagen { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
