//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int IdPersona { get; set; }
        public string IdTipoPersona { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Curp { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Genero { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string TelefonoMovil { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> IdSuscriptor { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Tipo { get; set; }
    }
}
