//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRP.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaneacionCaptura
    {
        public int IdPlaneacionCaptura { get; set; }
        public int IdAplicacion { get; set; }
        public int IdSuscriptor { get; set; }
        public string Descripcion { get; set; }
        public string TipoCaptura { get; set; }
        public string TipoEvento { get; set; }
        public string TipoPeriodo { get; set; }
        public string Periodicidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<System.TimeSpan> HoraInicial { get; set; }
        public Nullable<System.TimeSpan> HoraFinal { get; set; }
        public Nullable<short> IdEstatus { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
