//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaUsuario
    {
        public int IdUsuario { get; set; }
        public string Cuenta { get; set; }
        public string Contrasena { get; set; }
        public string IdEstacionTrabajo { get; set; }
        public Nullable<int> IdUsuarioSuperior { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public Nullable<System.DateTime> FechaCambioEstatus { get; set; }
        public string Tema { get; set; }
        public Nullable<short> IdEstatusUsuario { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<int> IdSuscriptor { get; set; }
        public Nullable<int> Sesiones { get; set; }
        public Nullable<int> Intentos { get; set; }
        public Nullable<int> IdIdioma { get; set; }
        public string Perfiles { get; set; }
        public string Grupos { get; set; }
        public Nullable<bool> Expira { get; set; }
        public string Privilegios { get; set; }
    }
}
