//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorio
    {
        public int id { get; set; }
        public string llave { get; set; }
        public string clave { get; set; }
        public string fecha { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idSubCategoria { get; set; }
        public Nullable<int> idGiro { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometria { get; set; }
        public string rutaFoto { get; set; }
        public string urlFoto { get; set; }
        public string urlVideo { get; set; }
        public string paginaWeb { get; set; }
        public string facebook { get; set; }
        public string youTube { get; set; }
        public string otraRedSocial { get; set; }
        public Nullable<int> idSuscriptor { get; set; }
        public string fechaEstatus { get; set; }
        public Nullable<short> estatus { get; set; }
    }
}
