//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlujoTrabajoDocumento
    {
        public int id { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idReferencia { get; set; }
        public Nullable<int> idActividad { get; set; }
        public string idAccion { get; set; }
        public string ruta { get; set; }
        public Nullable<System.DateTime> fechaEstatus { get; set; }
        public Nullable<short> estatus { get; set; }
    }
}
