//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenCarrusel
    {
        public int idImagen { get; set; }
        public string nombre { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public string ruta { get; set; }
        public int idSuscriptor { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
