//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripcion
    {
        public int IdSuscriptor { get; set; }
        public string NombreCorto { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaContratacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Servicios { get; set; }
        public Nullable<short> NumeroUsuarios { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdSuscriptorSuperior { get; set; }
        public string Descripcion { get; set; }
    }
}
